autoInstallPeers: true
allowBuilds:
  nx: true
  '@swc/core': true
  esbuild: true
  sharp: true
packages:
  - packages/*
  - packages/common/*
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - nx
  - sharp
minimumReleaseAgeExclude:
  - '@aws-sdk/lib-dynamodb'
  - '@cloudscape-design/component-toolkit'
  - '@smithy/core'
  - enhanced-resolve
catalogMode: strict
catalog:
  '@aws/nx-plugin': 1.0.0
  nx: 23.2.0
  '@nx/js': 23.2.0
  '@nx/workspace': 23.2.0
  typescript: ~6.0.3
  '@biomejs/biome': 2.5.12
  '@aws/nx-plugin-mcp': ^1.0.0
  husky: 9.1.7
  '@types/node': 26.4.1
  vite: 8.2.2
  vitest: 4.1.11
  '@vitest/coverage-v8': 4.1.11
  jsdom: 29.1.1
  '@nx/vitest': 23.2.0
  '@nx-extend/terraform': 10.4.1
  shx: 0.4.0
  tsx: 4.23.13
  '@aws-sdk/client-s3': 3.1126.0
  '@aws-sdk/client-sts': 3.1126.0
  '@aws-sdk/credential-providers': 3.1126.0
  '@smithy/config-resolver': 4.7.2
  '@smithy/node-config-provider': 4.6.2
  rolldown: 1.2.7
  aws-xray-sdk-core: 3.12.0
  zod: 4.5.4
  '@aws-lambda-powertools/logger': 2.35.0
  '@aws-lambda-powertools/metrics': 2.35.0
  '@aws-lambda-powertools/parameters': 2.35.0
  '@aws-lambda-powertools/tracer': 2.35.0
  '@aws-sdk/client-appconfigdata': 3.1126.0
  '@trpc/server': 11.18.0
  '@trpc/client': 11.18.0
  aws4fetch: 1.0.20
  '@types/aws-lambda': 8.10.163
  cors: 2.8.6
  '@types/cors': 2.8.19
  '@aws-sdk/client-dynamodb': 3.1126.0
  electrodb: 3.9.3
  react: 19.2.8
  react-dom: 19.2.8
  '@cloudscape-design/components': 3.0.1359
  '@cloudscape-design/board-components': 3.0.222
  '@cloudscape-design/global-styles': 1.0.67
  tailwindcss: 4.3.3
  '@tanstack/react-router': 1.170.32
  '@nx/react': 23.2.0
  '@vitest/ui': 4.1.11
  '@tailwindcss/vite': 4.3.3
  '@tanstack/router-plugin': 1.168.35
  '@tanstack/router-generator': 1.167.33
  '@tanstack/virtual-file-routes': 1.162.0
  '@tanstack/router-utils': 1.162.2
  oidc-client-ts: 3.5.0
  react-oidc-context: 3.3.1
  '@trpc/tanstack-react-query': 11.18.0
  '@tanstack/react-query': 5.102.8
  '@tanstack/react-query-devtools': 5.102.8
  event-source-polyfill: 1.0.31
  '@smithy/types': 4.18.0
  '@types/event-source-polyfill': 1.0.5
